server:
  port: 8080

spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
